version: "3.8"
services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dw
    ports:
      - "0.0.0.0:5434:5432"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "0.0.0.0:6381:6379"
    volumes:
      - "./redis:/data"
